### ISSUE TITLE
加入翻译

### ISSUE THREAD

**Issue by zuohuadong** [fastify/docs-chinese#11]
之前翻译了 nest.js 中文文档
我能参与翻译么？

**Comment by vincent178** [comment]
当然可以，欢迎欢迎。

你可以先fork这个项目，创建一个branch翻译某个文档，然后发一个PR给 @fralonra 或者我来review。尽量保证一个文章一个commit一个PR这样。

**Comment by fralonra** [comment]
欢迎加入翻译团队哈，简单流程就如上述了

我认为现在最好能确定一下 **翻译标准** 和 **风格规范**，作为协作的一个参考标准

#### 翻译标准主要内容
1. 确定主要概念的译法，包括：是否翻译、如何翻译等

#### 风格规范主要内容
1. 标点符号的转换建议，如是否转为中文符号、转换哪些

上述是我的一些建议，当然标准是可以被不断修订的哈，欢迎讨论
