### ISSUE TITLE
代码标点符号

### ISSUE THREAD

**Issue by lipengzhou** [fastify/docs-chinese#38]
刚看了第一篇起步，发现很多代码中的逗号都是中文全角。复制到编辑器中还需要手动修改为英文半角。

![image](https://user-images.githubusercontent.com/23165266/45066156-96e40b80-b0ef-11e8-8462-60ffff96a65b.png)
![image](https://user-images.githubusercontent.com/23165266/45066165-a2373700-b0ef-11e8-9593-18f0449b8cd2.png)

**Comment by fralonra** [comment]
感谢提出，会尽早改正！
