### ISSUE TITLE
翻译好评，fastify Apollo Graphql 的包哪里还有

### ISSUE THREAD

**Issue by zuohuadong** [fastify/docs-chinese#46]
之前 的仓库不维护了，现在 Apollo升级 2.0 。
只有 express 和 koa 有相关包，fastify 没有。。。

**Comment by fralonra** [comment]
暂时没有，可以自己把 express 等的插件拿过来套一下 fastify 的 api 直接使用

**Comment by fralonra** [comment]
https://github.com/codejie/fastify-apollo-step
@zuohuadong

**Comment by zuohuadong** [comment]
@fralonra 
感谢
但是不支持：  context: undefined,//not supported yet.
还是有点坑啊
打算从 express 切过来呢

**Comment by codejie** [comment]
> @fralonra
> 感谢
> 但是不支持： context: undefined,//not supported yet.
> 还是有点坑啊
> 打算从 express 切过来呢

context我这个没有用到，就没有深入跟踪，内部只是透传。
我这边项目是使用的fastify跟apollo结合，目前使用还没有发现问题。

**Comment by zuohuadong** [comment]
@codejie  要做七层权限管理。目前用的express ,
context 目前必须用到～
项目地址： https://github.com/notadd/nt-module-user

**Comment by codejie** [comment]
> @codejie 要做七层权限管理。目前用的express ,
> context 目前必须用到～
> 项目地址： https://github.com/notadd/nt-module-user

context是透传给apollo的，意味着，如果context是需要传给apollo服务，那就直接赋值就好。应跟直接使用apollo-server是一样的。
我这用了fastify做访问控制，因为它是通路，ql是数据。

**Comment by zuohuadong** [comment]
@codejie 能加下微信或者QQ吗？
最近还有个C的朋友，打算基于fastify一起做个 类似 kong 的API网关

**Comment by zuohuadong** [comment]
@codejie https://github.com/notadd/onenode/wiki/Roadmap  计划做这么一套东西～

**Comment by codejie** [comment]
> @codejie 能加下微信或者QQ吗？
> 最近还有个C的朋友，打算基于fastify一起做个 类似 kong 的API网关

不好意思，才看到回复，如需要，请添加105739071即可。
