### ISSUE TITLE
问大家个问题

### ISSUE THREAD

**Issue by luyouxin84** [fastify/docs-chinese#67]
大伙有没有发现，该框架在碰到错误的时候很容易就停下了？不像其他框架，只是抛出错误，但是不结束程序

**Comment by fralonra** [comment]
其他框架不太了解。可以举个例子吗（什么框架，如何避免结束程序）？

**Comment by vincent178** [comment]
@luyouxin84 有没有<b>最小可复现</b>的代码贴出来？
